// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/alexandremahdhaoui/forge/internal/cli"
)

// Version information (set via ldflags during build)
var (
	Version        = "dev"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

func main() {
	cli.Bootstrap(cli.Config{
		Name:           "go-lint-licenses",
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunMCP:         runMCPServer,
	})
}

// isGeneratedFile checks if a file is generated by reading its first non-empty line.
// Returns true if the first non-empty line starts with "// Code generated".
func isGeneratedFile(filePath string) (bool, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return false, err
	}
	defer func() { _ = file.Close() }()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		// Skip empty lines
		if line == "" {
			continue
		}
		// Check first non-empty line
		return strings.HasPrefix(line, "// Code generated"), nil
	}

	if err := scanner.Err(); err != nil {
		return false, err
	}

	// Empty file - not generated
	return false, nil
}

// findGoFiles recursively finds all *.go files, skipping vendor, .git, .tmp, node_modules directories
// and generated files.
func findGoFiles(root string) ([]string, error) {
	var goFiles []string

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Skip vendor, .git, .tmp, node_modules directories
		if info.IsDir() {
			name := info.Name()
			if name == "vendor" || name == ".git" || name == ".tmp" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}

		// Check if it's a Go file
		if strings.HasSuffix(path, ".go") {
			// Skip generated files
			isGenerated, err := isGeneratedFile(path)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: could not check if %s is generated: %v\n", path, err)
				// Include the file anyway if we can't determine
				goFiles = append(goFiles, path)
				return nil
			}
			if !isGenerated {
				goFiles = append(goFiles, path)
			}
		}

		return nil
	})

	return goFiles, err
}

// hasLicenseHeader checks if a file has a license header in its first 15 lines.
// Returns true if any line contains "// Copyright", "// SPDX-License-Identifier", or "// Licensed under".
// Returns false if "package " is encountered before a license or 15 lines are exceeded.
func hasLicenseHeader(filePath string) (bool, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return false, err
	}
	defer func() { _ = file.Close() }()

	scanner := bufio.NewScanner(file)

	lineCount := 0
	for scanner.Scan() && lineCount < 15 {
		line := scanner.Text()
		lineCount++

		// Check for license patterns
		if strings.Contains(line, "// Copyright") ||
			strings.Contains(line, "// SPDX-License-Identifier") ||
			strings.Contains(line, "// Licensed under") {
			return true, nil
		}

		// Stop at package declaration
		if strings.HasPrefix(strings.TrimSpace(line), "package ") {
			break
		}
	}

	if err := scanner.Err(); err != nil {
		return false, err
	}

	return false, nil
}

// verifyLicenses performs the license verification and returns results.
// Returns (filesWithoutLicense, totalFiles, error).
func verifyLicenses(rootDir string) ([]string, int, error) {
	// Find all Go files
	goFiles, err := findGoFiles(rootDir)
	if err != nil {
		return nil, 0, fmt.Errorf("error finding Go files: %w", err)
	}

	if len(goFiles) == 0 {
		return []string{}, 0, nil
	}

	// Verify each Go file has a license header
	var filesWithoutLicense []string
	for _, file := range goFiles {
		hasLicense, err := hasLicenseHeader(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error checking %s: %v\n", file, err)
			continue
		}
		if !hasLicense {
			filesWithoutLicense = append(filesWithoutLicense, file)
		}
	}

	return filesWithoutLicense, len(goFiles), nil
}
