// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:895662149574b0093b3df579d8201af374f2c6ccf78055f0634512c0fe215f25

package main

import (
	"fmt"
)

// Spec contains the configuration for this engine.
// These fields are populated from the 'spec' field in forge.yaml.
type Spec struct {
	// Patterns to exclude from scanning (optional, currently unused)
	ExcludePatterns []string `json:"excludePatterns,omitempty"`
	// Root directory to scan for Go files (optional, currently unused)
	RootDir string `json:"rootDir,omitempty"`
}

// FromMap creates a Spec from a map[string]interface{}.
// This is used to parse the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// Parse excludePatterns
	if v, ok := m["excludePatterns"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ExcludePatterns = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.ExcludePatterns = append(s.ExcludePatterns, str)
				} else {
					return nil, fmt.Errorf("field excludePatterns[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.ExcludePatterns = arr
		} else {
			return nil, fmt.Errorf("field excludePatterns: expected []string, got %T", v)
		}
	}

	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}

	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
// This is used for serialization and testing.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})

	if len(s.ExcludePatterns) > 0 {
		m["excludePatterns"] = s.ExcludePatterns
	}

	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}

	return m
}
