// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:0305f58657cd7f107a55fbb24997ef1bba6aa2f5879bd85c571d756c3752b954

package main

import (
	"fmt"
)

// Spec contains the configuration for this engine.
// These fields are populated from the 'spec' field in forge.yaml.
type Spec struct {
	// Working directory for mock detection (optional)
	WorkDir string `json:"workDir,omitempty"`
}

// FromMap creates a Spec from a map[string]interface{}.
// This is used to parse the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// Parse workDir
	if v, ok := m["workDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.WorkDir = val
		} else {
			return nil, fmt.Errorf("field workDir: expected string, got %T", v)
		}
	}

	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
// This is used for serialization and testing.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})

	if s.WorkDir != "" {
		m["workDir"] = s.WorkDir
	}

	return m
}
