// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: sha256:79c843541eeef5d9f3ca8212219f777dce4d6ae6600d46afde9d1e20d77c0de1

package main

import (
	"github.com/alexandremahdhaoui/forge/pkg/enginedocs"
	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
)

// docsConfig is the configuration for documentation tools.
var docsConfig = &enginedocs.Config{
	EngineName:   "go-format",
	LocalDir:     "cmd/go-format/docs",
	BaseURL:      "https://raw.githubusercontent.com/alexandremahdhaoui/forge/refs/heads/main",
	RequiredDocs: []string{"usage", "schema"},
}

// RegisterDocsMCPTools registers the docs-list and docs-get MCP tools.
func RegisterDocsMCPTools(server *mcpserver.Server) error {
	return enginedocs.RegisterDocsTools(server, *docsConfig)
}
