// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:1b06c15264d055a0c8b418c05193086798c96f73e0d6c51f028fee1b10fc8321

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for go-format engine
type Spec struct {
	// Path to format (optional, defaults to src or current directory)
	Path string `json:"path,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Path != "" {
		m["path"] = s.Path
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
