// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:9ec9a0bf5b203e47f61316fc199c819293c5ddb0dc57c9e851c1261400bfb5d0

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for go-gen-mocks. Uses mockery for mock generation.
type Spec struct {
	// Version of mockery to use (default v3.5.5)
	MockeryVersion string `json:"mockeryVersion,omitempty"`
	// Directory where mocks should be generated (default from MOCKS_DIR env)
	MocksDir string `json:"mocksDir,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}
	// Parse mockeryVersion
	if v, ok := m["mockeryVersion"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.MockeryVersion = val
		} else {
			return nil, fmt.Errorf("field mockeryVersion: expected string, got %T", v)
		}
	}
	// Parse mocksDir
	if v, ok := m["mocksDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.MocksDir = val
		} else {
			return nil, fmt.Errorf("field mocksDir: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.MockeryVersion != "" {
		m["mockeryVersion"] = s.MockeryVersion
	}
	if s.MocksDir != "" {
		m["mocksDir"] = s.MocksDir
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
