// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:manual-migration-testenv-helm-install

package main

// Spec contains the configuration for this engine.
// These fields are populated from the 'spec' field in forge.yaml.
// Note: The charts array is parsed separately using parseChartsFromSpec.
type Spec struct {
	// Spec is intentionally empty as charts are parsed via parseChartsFromSpec.
	// This type exists for API consistency with other testenv subengines.
}

// FromMap creates a Spec from a map[string]interface{}.
// This is used to parse the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	// Spec is empty - charts are parsed separately via parseChartsFromSpec
	return &Spec{}, nil
}

// ToMap converts a Spec to a map[string]interface{}.
// This is used for serialization and testing.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}
	return make(map[string]interface{})
}
