// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:manual-migration-go-lint-tags

package main

import (
	"fmt"
)

// Spec contains the configuration for this engine.
// These fields are populated from the 'spec' field in forge.yaml.
type Spec struct {
	// List of expected build tags to check for (default is unit, integration, e2e)
	ExpectedTags []string `json:"expectedTags,omitempty"`
	// Root directory to scan for test files (default is current directory)
	RootDir string `json:"rootDir,omitempty"`
}

// FromMap creates a Spec from a map[string]interface{}.
// This is used to parse the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// Parse expectedTags
	if v, ok := m["expectedTags"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ExpectedTags = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.ExpectedTags = append(s.ExpectedTags, str)
				} else {
					return nil, fmt.Errorf("field expectedTags[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.ExpectedTags = arr
		} else {
			return nil, fmt.Errorf("field expectedTags: expected []string, got %T", v)
		}
	}

	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}

	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
// This is used for serialization and testing.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})

	if len(s.ExpectedTags) > 0 {
		m["expectedTags"] = s.ExpectedTags
	}

	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}

	return m
}
