// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:35fb3014deff846764e50ba8c7a75053b8a0e434c4316dad0004e313d41012e2

package main

import (
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// Validate validates a Spec and returns validation results.
// It checks required fields and validates enum values.
func Validate(s *Spec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	// No required fields or enum validations for go-lint spec
	// All fields are optional

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateMap validates a map[string]interface{} by first parsing it to a Spec.
// This is a convenience function for validating spec data from forge.yaml.
func ValidateMap(m map[string]interface{}) *mcptypes.ConfigValidateOutput {
	s, err := FromMap(m)
	if err != nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: false,
			Errors: []mcptypes.ValidationError{
				{
					Field:   "spec",
					Message: err.Error(),
				},
			},
		}
	}

	return Validate(s)
}
