// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:83db4ec75b9aec7fa596d1e524ebf027dd752e3c3d655770904cc873772b703b

package main

import (
	"fmt"
)

// Spec contains the configuration for this engine.
// These fields are populated from the 'spec' field in forge.yaml.
type Spec struct {
	// Additional arguments to pass to golangci-lint (optional)
	Args []string `json:"args,omitempty"`
	// Path to golangci-lint config file (optional)
	Config string `json:"config,omitempty"`
}

// FromMap creates a Spec from a map[string]interface{}.
// This is used to parse the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// Parse args
	if v, ok := m["args"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Args = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Args = append(s.Args, str)
				} else {
					return nil, fmt.Errorf("field args[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Args = arr
		} else {
			return nil, fmt.Errorf("field args: expected []string, got %T", v)
		}
	}

	// Parse config
	if v, ok := m["config"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Config = val
		} else {
			return nil, fmt.Errorf("field config: expected string, got %T", v)
		}
	}

	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
// This is used for serialization and testing.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})

	if len(s.Args) > 0 {
		m["args"] = s.Args
	}

	if s.Config != "" {
		m["config"] = s.Config
	}

	return m
}
