// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml + spec.openapi.yaml
// SourceChecksum: sha256:4464b4dbd2317db5472a1aa4ee172eff9697c3f614b1c3ac23e5741344986a47

package main

import (
	"context"

	"github.com/alexandremahdhaoui/forge/pkg/enginecli"
	"github.com/alexandremahdhaoui/forge/pkg/forge"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// Name is the engine name.
const Name = "parallel-builder"

// Version information (set via ldflags during build).
var (
	Version        = "0.15.0"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

// main is the entry point for the parallel-builder engine.
func main() {
	enginecli.Bootstrap(enginecli.Config{
		Name:           Name,
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunCLI:         nil, // Generated engines are MCP-only
		RunMCP:         runMCPServer,
		DocsConfig:     docsConfig,
	})
}

// NOTE: Custom runMCPServer is defined in mcp.go for recursive config-validate registration

// Build is the build function that must be implemented by the engine author.
// Signature: func(ctx context.Context, input mcptypes.BuildInput, spec *Spec) (*forge.Artifact, error)
// This is a placeholder - the actual implementation should be in a separate file.
var _ = func() BuildFunc {
	return func(_ context.Context, _ mcptypes.BuildInput, _ *Spec) (*forge.Artifact, error) {
		panic("Build function not implemented - create a separate file with the implementation")
	}
}
