// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:4464b4dbd2317db5472a1aa4ee172eff9697c3f614b1c3ac23e5741344986a47

package main

// Spec contains the configuration for this engine.
// These fields are populated from the 'spec' field in forge.yaml.
type Spec struct {
	// List of sub-builder configurations to run in parallel. Each item must be an object with 'engine' (required), 'name' (optional), and 'spec' (optional) fields.
	Builders []interface{} `json:"builders"`
}

// FromMap creates a Spec from a map[string]interface{}.
// This is used to parse the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// Parse builders
	if v, ok := m["builders"]; ok && v != nil {
		// Unsupported type []interface{} - store as-is
		_ = v
	}

	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
// This is used for serialization and testing.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})

	// Unsupported type []interface{}

	return m
}
