// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: sha256:0f6c7423835997be98586057d3377f81f6c003e1a158946ba3bf815b69950605

package main

import (
	"github.com/alexandremahdhaoui/forge/pkg/enginedocs"
	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
)

// docsConfig is the configuration for documentation tools.
var docsConfig = &enginedocs.Config{
	EngineName:   "testenv-kind",
	LocalDir:     "cmd/testenv-kind/docs",
	BaseURL:      "https://raw.githubusercontent.com/alexandremahdhaoui/forge/refs/heads/main",
	RequiredDocs: []string{"usage", "schema"},
}

// RegisterDocsMCPTools registers the docs-list and docs-get MCP tools.
func RegisterDocsMCPTools(server *mcpserver.Server) error {
	return enginedocs.RegisterDocsTools(server, *docsConfig)
}
