// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:manual-migration-testenv-kind

package main

import (
	"fmt"
)

// Spec contains the configuration for this engine.
// These fields are populated from the 'spec' field in forge.yaml.
type Spec struct {
	// Custom name suffix for the kind cluster (default uses test ID)
	Name string `json:"name,omitempty"`
	// Kind node image to use (e.g., kindest/node:v1.27.0)
	Image string `json:"image,omitempty"`
	// Path to kind config file for cluster customization
	Config string `json:"config,omitempty"`
	// Timeout for waiting for cluster to be ready (e.g., 5m)
	WaitTimeout string `json:"waitTimeout,omitempty"`
	// Whether to retain the cluster on failure for debugging
	Retain bool `json:"retain,omitempty"`
}

// FromMap creates a Spec from a map[string]interface{}.
// This is used to parse the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}

	// Parse image
	if v, ok := m["image"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Image = val
		} else {
			return nil, fmt.Errorf("field image: expected string, got %T", v)
		}
	}

	// Parse config
	if v, ok := m["config"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Config = val
		} else {
			return nil, fmt.Errorf("field config: expected string, got %T", v)
		}
	}

	// Parse waitTimeout
	if v, ok := m["waitTimeout"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.WaitTimeout = val
		} else {
			return nil, fmt.Errorf("field waitTimeout: expected string, got %T", v)
		}
	}

	// Parse retain
	if v, ok := m["retain"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Retain = val
		} else {
			return nil, fmt.Errorf("field retain: expected bool, got %T", v)
		}
	}

	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
// This is used for serialization and testing.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})

	if s.Name != "" {
		m["name"] = s.Name
	}

	if s.Image != "" {
		m["image"] = s.Image
	}

	if s.Config != "" {
		m["config"] = s.Config
	}

	if s.WaitTimeout != "" {
		m["waitTimeout"] = s.WaitTimeout
	}

	if s.Retain {
		m["retain"] = s.Retain
	}

	return m
}
