package mcptypes

import (
	"github.com/alexandremahdhaoui/forge/pkg/forge"
)

// DirectoryParams contains standardized directory paths passed from forge to engines/runners.
type DirectoryParams struct {
	TmpDir   string `json:"tmpDir,omitempty"`   // Temporary directory for non-build artifacts (e.g., test reports)
	BuildDir string `json:"buildDir,omitempty"` // Build directory for build outputs (e.g., binaries)
	RootDir  string `json:"rootDir,omitempty"`  // Repository root directory (for code generation)
}

// RunInput represents the standard input parameters for test runner tools.
// This is used across all test runners (go-test, generic-test-runner, etc.).
type RunInput struct {
	ID      string            `json:"id"`                // Report ID (UUID, generated by forge and passed to runner)
	Stage   string            `json:"stage"`             // Test stage name (required)
	Name    string            `json:"name"`              // Test name (required)
	Command string            `json:"command,omitempty"` // Command to execute (optional, for generic runner)
	Args    []string          `json:"args,omitempty"`    // Command arguments (optional, for generic runner)
	Env     map[string]string `json:"env,omitempty"`     // Environment variables (optional, for generic runner)
	EnvFile string            `json:"envFile,omitempty"` // Path to environment file (optional, for generic runner)
	WorkDir string            `json:"workDir,omitempty"` // Working directory (optional, for generic runner)

	// Artifact files from testenv (e.g., kubeconfig, registry credentials)
	ArtifactFiles map[string]string `json:"artifactFiles,omitempty"` // Map of file key to relative path (relative to testenvTmpDir)

	// Testenv tmpDir (where artifact files are located)
	TestenvTmpDir string `json:"testenvTmpDir,omitempty"` // Absolute path to testenv's tmpDir

	// Testenv metadata (e.g., cluster name, registry URL)
	TestenvMetadata map[string]string `json:"testenvMetadata,omitempty"` // Map of metadata key to value

	// Testenv environment variables (propagated from testenv chain)
	TestenvEnv map[string]string `json:"testenvEnv,omitempty"` // Map of env var name to value

	// EnvPropagation configuration for filtering testenv environment variables
	EnvPropagation *forge.EnvPropagation `json:"envPropagation,omitempty"`

	// Directory parameters (injected by forge)
	DirectoryParams
}

// BuildInput represents the standard input parameters for build engine tools.
// This is used across all build engines (go-build, container-build, generic-builder, etc.).
type BuildInput struct {
	Name   string `json:"name"`           // Artifact name (required)
	Src    string `json:"src,omitempty"`  // Source path
	Dest   string `json:"dest,omitempty"` // Destination path
	Engine string `json:"engine"`         // Engine identifier

	// Generic engine specific fields (optional)
	Command string            `json:"command,omitempty"` // Command to execute
	Args    []string          `json:"args,omitempty"`    // Command arguments
	Env     map[string]string `json:"env,omitempty"`     // Environment variables
	EnvFile string            `json:"envFile,omitempty"` // Path to environment file
	WorkDir string            `json:"workDir,omitempty"` // Working directory

	// Format-go specific fields (optional)
	Path string `json:"path,omitempty"` // Path to format

	// Spec contains engine-specific configuration (free-form, alternative to individual fields)
	// When present, engines should prefer spec fields over individual Args/Env fields
	// This allows passing configuration from BuildSpec.Spec directly through MCP
	//
	// Example for go-gen-openapi engine:
	//   spec: {
	//     "sourceFile": "./api/example-api.v1.yaml",
	//     "destinationDir": "./pkg/generated",
	//     "client": {
	//       "enabled": true,
	//       "packageName": "exampleclient"
	//     },
	//     "server": {
	//       "enabled": false
	//     }
	//   }
	//
	// Engines define their own Spec structure. See individual engine MCP documentation for details.
	Spec map[string]interface{} `json:"spec,omitempty"`

	// Directory parameters (injected by forge)
	DirectoryParams
}

// BatchBuildInput represents the input for building multiple artifacts in batch.
type BatchBuildInput struct {
	Specs []BuildInput `json:"specs"` // List of build specifications
}

// DetectDependenciesInput represents the standard input parameters for dependency-detector tools.
// This is used across all dependency detectors (go-dependency-detector, etc.).
type DetectDependenciesInput struct {
	FilePath string `json:"filePath"` // Path to source file to analyze (absolute path)
	FuncName string `json:"funcName"` // Name of function to analyze (e.g., "main")

	// Spec contains engine-specific configuration (free-form)
	// The exact fields supported depend on the engine being used
	Spec map[string]interface{} `json:"spec,omitempty"`

	// Directory parameters (injected by forge)
	DirectoryParams
}

// Dependency represents a single dependency detected by a dependency-detector engine.
// This is the MCP wire format, matching ArtifactDependency from pkg/forge/artifact_store.go.
type Dependency struct {
	// Type is either "file" or "externalPackage"
	Type string `json:"type"`
	// FilePath is the absolute path to file dependency (if Type=file)
	FilePath string `json:"filePath,omitempty"`
	// ExternalPackage is the package identifier (if Type=externalPackage, e.g., "github.com/foo/bar")
	ExternalPackage string `json:"externalPackage,omitempty"`
	// Timestamp is RFC3339 timestamp in UTC (if Type=file, e.g., "2025-11-23T10:00:00Z")
	Timestamp string `json:"timestamp,omitempty"`
	// Semver is semantic version (if Type=externalPackage, supports pseudo-versions like "v0.0.0-20231010123456-abcdef123456")
	Semver string `json:"semver,omitempty"`
}

// DetectDependenciesOutput represents the output from dependency-detector tools.
type DetectDependenciesOutput struct {
	Dependencies []Dependency `json:"dependencies"` // List of detected dependencies
}
