// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:1328f7d67b9ef7689d80c4733ec8e6f7d86b62e0637ea4d05ad4159b0ff814c6

package main

import (
	"fmt"
)

// Spec contains the configuration for this engine.
// These fields are populated from the 'spec' field in forge.yaml.
type Spec struct {
	// Whether to resolve external references
	ResolveRefs bool `json:"resolveRefs,omitempty"`
	// Root directory for resolving relative paths
	RootDir string `json:"rootDir,omitempty"`
	// OpenAPI spec file paths to scan
	SpecSources []string `json:"specSources,omitempty"`
}

// FromMap creates a Spec from a map[string]interface{}.
// This is used to parse the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// Parse resolveRefs
	if v, ok := m["resolveRefs"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.ResolveRefs = val
		} else {
			return nil, fmt.Errorf("field resolveRefs: expected bool, got %T", v)
		}
	}

	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}

	// Parse specSources
	if v, ok := m["specSources"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.SpecSources = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.SpecSources = append(s.SpecSources, str)
				} else {
					return nil, fmt.Errorf("field specSources[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.SpecSources = arr
		} else {
			return nil, fmt.Errorf("field specSources: expected []string, got %T", v)
		}
	}

	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
// This is used for serialization and testing.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})

	if s.ResolveRefs {
		m["resolveRefs"] = s.ResolveRefs
	}

	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}

	if len(s.SpecSources) > 0 {
		m["specSources"] = s.SpecSources
	}

	return m
}
