//go:build unit

// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestComputeSourceChecksum(t *testing.T) {
	t.Run("consistent results for same inputs", func(t *testing.T) {
		dir := t.TempDir()

		configPath := filepath.Join(dir, "forge-dev.yaml")
		specPath := filepath.Join(dir, "spec.openapi.yaml")

		configContent := "name: test\ntype: builder\n"
		specContent := "openapi: 3.0.3\ninfo:\n  title: Test\n"

		if err := os.WriteFile(configPath, []byte(configContent), 0o644); err != nil {
			t.Fatalf("failed to write config file: %v", err)
		}
		if err := os.WriteFile(specPath, []byte(specContent), 0o644); err != nil {
			t.Fatalf("failed to write spec file: %v", err)
		}

		// Compute checksum twice
		checksum1, err := ComputeSourceChecksum(configPath, specPath)
		if err != nil {
			t.Fatalf("ComputeSourceChecksum failed: %v", err)
		}

		checksum2, err := ComputeSourceChecksum(configPath, specPath)
		if err != nil {
			t.Fatalf("ComputeSourceChecksum failed: %v", err)
		}

		if checksum1 != checksum2 {
			t.Errorf("Checksums differ for same inputs: %q != %q", checksum1, checksum2)
		}

		// Verify checksum format
		if !strings.HasPrefix(checksum1, ChecksumPrefix) {
			t.Errorf("Checksum should start with %q, got %q", ChecksumPrefix, checksum1)
		}

		// Verify hex format after prefix (SHA256 = 64 hex chars)
		hexPart := strings.TrimPrefix(checksum1, ChecksumPrefix)
		if len(hexPart) != 64 {
			t.Errorf("Expected 64 hex characters, got %d", len(hexPart))
		}
	})

	t.Run("different results for different inputs", func(t *testing.T) {
		dir := t.TempDir()

		configPath := filepath.Join(dir, "forge-dev.yaml")
		specPath := filepath.Join(dir, "spec.openapi.yaml")

		// First set of inputs
		if err := os.WriteFile(configPath, []byte("name: test1"), 0o644); err != nil {
			t.Fatalf("failed to write config file: %v", err)
		}
		if err := os.WriteFile(specPath, []byte("openapi: 3.0.3"), 0o644); err != nil {
			t.Fatalf("failed to write spec file: %v", err)
		}

		checksum1, err := ComputeSourceChecksum(configPath, specPath)
		if err != nil {
			t.Fatalf("ComputeSourceChecksum failed: %v", err)
		}

		// Different config content
		if err := os.WriteFile(configPath, []byte("name: test2"), 0o644); err != nil {
			t.Fatalf("failed to write config file: %v", err)
		}

		checksum2, err := ComputeSourceChecksum(configPath, specPath)
		if err != nil {
			t.Fatalf("ComputeSourceChecksum failed: %v", err)
		}

		if checksum1 == checksum2 {
			t.Error("Checksums should differ for different config content")
		}

		// Different spec content
		if err := os.WriteFile(configPath, []byte("name: test1"), 0o644); err != nil { // Reset config
			t.Fatalf("failed to write config file: %v", err)
		}
		if err := os.WriteFile(specPath, []byte("openapi: 3.1.0"), 0o644); err != nil {
			t.Fatalf("failed to write spec file: %v", err)
		}

		checksum3, err := ComputeSourceChecksum(configPath, specPath)
		if err != nil {
			t.Fatalf("ComputeSourceChecksum failed: %v", err)
		}

		if checksum1 == checksum3 {
			t.Error("Checksums should differ for different spec content")
		}
	})

	t.Run("error on missing config file", func(t *testing.T) {
		dir := t.TempDir()
		specPath := filepath.Join(dir, "spec.openapi.yaml")

		if err := os.WriteFile(specPath, []byte("openapi: 3.0.3"), 0o644); err != nil {
			t.Fatalf("failed to write spec file: %v", err)
		}

		_, err := ComputeSourceChecksum(filepath.Join(dir, "nonexistent.yaml"), specPath)
		if err == nil {
			t.Error("Expected error for missing config file")
		}
	})

	t.Run("error on missing spec file", func(t *testing.T) {
		dir := t.TempDir()
		configPath := filepath.Join(dir, "forge-dev.yaml")

		if err := os.WriteFile(configPath, []byte("name: test"), 0o644); err != nil {
			t.Fatalf("failed to write config file: %v", err)
		}

		_, err := ComputeSourceChecksum(configPath, filepath.Join(dir, "nonexistent.yaml"))
		if err == nil {
			t.Error("Expected error for missing spec file")
		}
	})
}

func TestReadChecksumFromFile(t *testing.T) {
	t.Run("extract checksum from header", func(t *testing.T) {
		dir := t.TempDir()
		filePath := filepath.Join(dir, "zz_generated.spec.go")

		fileContent := `// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

package main

type Spec struct {
}
`
		if err := os.WriteFile(filePath, []byte(fileContent), 0o644); err != nil {
			t.Fatalf("failed to write file: %v", err)
		}

		checksum, err := ReadChecksumFromFile(filePath)
		if err != nil {
			t.Fatalf("ReadChecksumFromFile failed: %v", err)
		}

		expected := "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
		if checksum != expected {
			t.Errorf("Checksum = %q, want %q", checksum, expected)
		}
	})

	t.Run("no checksum in file", func(t *testing.T) {
		dir := t.TempDir()
		filePath := filepath.Join(dir, "file.go")

		fileContent := `// Some other comment
package main

func main() {}
`
		if err := os.WriteFile(filePath, []byte(fileContent), 0o644); err != nil {
			t.Fatalf("failed to write file: %v", err)
		}

		checksum, err := ReadChecksumFromFile(filePath)
		if err != nil {
			t.Fatalf("ReadChecksumFromFile failed: %v", err)
		}

		if checksum != "" {
			t.Errorf("Expected empty checksum, got %q", checksum)
		}
	})

	t.Run("file does not exist", func(t *testing.T) {
		checksum, err := ReadChecksumFromFile("/nonexistent/path/file.go")
		if err != nil {
			t.Errorf("Should not error for nonexistent file, got: %v", err)
		}
		if checksum != "" {
			t.Errorf("Expected empty checksum for nonexistent file, got %q", checksum)
		}
	})

	t.Run("checksum on later line", func(t *testing.T) {
		dir := t.TempDir()
		filePath := filepath.Join(dir, "file.go")

		fileContent := `// Code generated by forge-dev. DO NOT EDIT.
// First comment line
// Second comment line
// Third comment line
// SourceChecksum: sha256:abcd1234567890

package main
`
		if err := os.WriteFile(filePath, []byte(fileContent), 0o644); err != nil {
			t.Fatalf("failed to write file: %v", err)
		}

		checksum, err := ReadChecksumFromFile(filePath)
		if err != nil {
			t.Fatalf("ReadChecksumFromFile failed: %v", err)
		}

		expected := "sha256:abcd1234567890"
		if checksum != expected {
			t.Errorf("Checksum = %q, want %q", checksum, expected)
		}
	})

	t.Run("stops after non-comment line", func(t *testing.T) {
		dir := t.TempDir()
		filePath := filepath.Join(dir, "file.go")

		fileContent := `// Some comment
package main

// SourceChecksum: sha256:should-not-find-this
`
		if err := os.WriteFile(filePath, []byte(fileContent), 0o644); err != nil {
			t.Fatalf("failed to write file: %v", err)
		}

		checksum, err := ReadChecksumFromFile(filePath)
		if err != nil {
			t.Fatalf("ReadChecksumFromFile failed: %v", err)
		}

		if checksum != "" {
			t.Errorf("Expected empty checksum (after package line), got %q", checksum)
		}
	})
}

func TestChecksumHeader(t *testing.T) {
	checksum := "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
	expected := "// SourceChecksum: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

	result := ChecksumHeader(checksum)
	if result != expected {
		t.Errorf("ChecksumHeader(%q) = %q, want %q", checksum, result, expected)
	}
}

func TestChecksumMatches(t *testing.T) {
	t.Run("matching checksums", func(t *testing.T) {
		checksum := "sha256:abc123"
		if !ChecksumMatches(checksum, checksum) {
			t.Error("Identical checksums should match")
		}
	})

	t.Run("different checksums", func(t *testing.T) {
		if ChecksumMatches("sha256:abc123", "sha256:def456") {
			t.Error("Different checksums should not match")
		}
	})

	t.Run("empty computed checksum", func(t *testing.T) {
		if ChecksumMatches("", "sha256:abc123") {
			t.Error("Empty computed checksum should not match")
		}
	})

	t.Run("empty existing checksum", func(t *testing.T) {
		if ChecksumMatches("sha256:abc123", "") {
			t.Error("Empty existing checksum should not match")
		}
	})

	t.Run("both empty", func(t *testing.T) {
		if ChecksumMatches("", "") {
			t.Error("Both empty should not match")
		}
	})
}

func TestChecksumRoundTrip(t *testing.T) {
	// Test that we can compute a checksum, write it to a file, and read it back
	dir := t.TempDir()

	configPath := filepath.Join(dir, "forge-dev.yaml")
	specPath := filepath.Join(dir, "spec.openapi.yaml")
	generatedPath := filepath.Join(dir, "zz_generated.spec.go")

	// Create source files
	if err := os.WriteFile(configPath, []byte("name: test"), 0o644); err != nil {
		t.Fatalf("failed to write config file: %v", err)
	}
	if err := os.WriteFile(specPath, []byte("openapi: 3.0.3"), 0o644); err != nil {
		t.Fatalf("failed to write spec file: %v", err)
	}

	// Compute checksum
	checksum, err := ComputeSourceChecksum(configPath, specPath)
	if err != nil {
		t.Fatalf("ComputeSourceChecksum failed: %v", err)
	}

	// Write "generated" file with checksum header
	generatedContent := `// Code generated by forge-dev. DO NOT EDIT.
` + ChecksumHeader(checksum) + `

package main

type Spec struct {}
`
	if err := os.WriteFile(generatedPath, []byte(generatedContent), 0o644); err != nil {
		t.Fatalf("failed to write generated file: %v", err)
	}

	// Read checksum back
	readChecksum, err := ReadChecksumFromFile(generatedPath)
	if err != nil {
		t.Fatalf("ReadChecksumFromFile failed: %v", err)
	}

	// Verify they match
	if !ChecksumMatches(checksum, readChecksum) {
		t.Errorf("Round-trip checksum mismatch: computed=%q, read=%q", checksum, readChecksum)
	}
}
