// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml + spec.openapi.yaml
// SourceChecksum: sha256:52b14b5cea709c37bdef55327f0ade8ee47c980ab36532ec9c53e559f611223e

package main

import (
	"context"

	"github.com/alexandremahdhaoui/forge/pkg/enginecli"
	"github.com/alexandremahdhaoui/forge/pkg/forge"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// Ensure imports are used (referenced by run.go and mcp.go)
var (
	_ context.Context
	_ *forge.TestReport
	_ mcptypes.RunInput
)

// Name is the engine name.
const Name = "parallel-test-runner"

// Version information (set via ldflags during build).
var (
	Version        = "0.15.0"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

// main is the entry point for the parallel-test-runner engine.
func main() {
	enginecli.Bootstrap(enginecli.Config{
		Name:           Name,
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunCLI:         nil, // Generated engines are MCP-only
		RunMCP:         runMCPServer,
		DocsConfig:     docsConfig,
	})
}

// runMCPServer is defined in mcp.go with custom config-validate registration.

// Run is the run function that must be implemented by the engine author.
// Signature: func(ctx context.Context, input mcptypes.RunInput, spec *Spec) (*forge.TestReport, error)
// This is a placeholder - the actual implementation should be in a separate file.
var _ = func() TestRunnerFunc {
	return func(_ context.Context, _ mcptypes.RunInput, _ *Spec) (*forge.TestReport, error) {
		panic("Run function not implemented - create a separate file with the implementation")
	}
}
