// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:20400a9916cb69791cf3bffafa3f4a82d3d92ef62fa2ea5197d7efd4863cdb45

package main

import (
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// ValidateSpec validates a Spec and returns validation results.
// It checks required fields and validates enum values.
func ValidateSpec(s *Spec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// Validate validates a Spec and returns validation results.
// This is the main entry point for validation.
func Validate(s *Spec) *mcptypes.ConfigValidateOutput {
	return ValidateSpec(s)
}

// ValidateMap validates a map[string]interface{} by first parsing it to a Spec.
// This is a convenience function for validating spec data from forge.yaml.
func ValidateMap(m map[string]interface{}) *mcptypes.ConfigValidateOutput {
	s, err := FromMap(m)
	if err != nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: false,
			Errors: []mcptypes.ValidationError{
				{
					Field:   "spec",
					Message: err.Error(),
				},
			},
		}
	}

	return Validate(s)
}
