// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml + spec.openapi.yaml
// SourceChecksum: sha256:c0619ca0baa98fb2b1070a1f981604dfb7b19c4dc20d9e270002498df5d314db

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/enginecli"
	"github.com/alexandremahdhaoui/forge/pkg/forge"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// Name is the engine name.
const Name = "forge-e2e"

// Version information (set via ldflags during build).
var (
	Version        = "0.15.0"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

// main is the entry point for the forge-e2e engine.
func main() {
	enginecli.Bootstrap(enginecli.Config{
		Name:           Name,
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunCLI:         nil, // Generated engines are MCP-only
		RunMCP:         runMCPServer,
		DocsConfig:     docsConfig,
	})
}

// runMCPServer creates and runs the MCP server.
func runMCPServer() error {
	server, err := SetupMCPServer(Name, Version, Run)
	if err != nil {
		return fmt.Errorf("setting up MCP server: %w", err)
	}

	// Register docs MCP tools (docs-list, docs-get)
	if err := RegisterDocsMCPTools(server); err != nil {
		return fmt.Errorf("registering docs MCP tools: %w", err)
	}

	if err := server.Run(context.Background()); err != nil {
		return fmt.Errorf("running MCP server: %w", err)
	}

	return nil
}

// Run is the run function that must be implemented by the engine author.
// Signature: func(ctx context.Context, input mcptypes.RunInput, spec *Spec) (*forge.TestReport, error)
// This is a placeholder - the actual implementation should be in a separate file.
var _ = func() TestRunnerFunc {
	return func(_ context.Context, _ mcptypes.RunInput, _ *Spec) (*forge.TestReport, error) {
		panic("Run function not implemented - create a separate file with the implementation")
	}
}
