// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:8d20a6cfab2fb4622603c599d541f447713431484827f048c7f8fd6cc6269e94

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for go-gen-openapi. Uses oapi-codegen for code generation.
type Spec struct {
	// Version of oapi-codegen to use (default v2.3.0)
	OapiCodegenVersion string `json:"oapiCodegenVersion,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}
	// Parse oapiCodegenVersion
	if v, ok := m["oapiCodegenVersion"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.OapiCodegenVersion = val
		} else {
			return nil, fmt.Errorf("field oapiCodegenVersion: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.OapiCodegenVersion != "" {
		m["oapiCodegenVersion"] = s.OapiCodegenVersion
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
