// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:manual-migration-go-gen-openapi

package main

import (
	"fmt"
)

// Spec contains the configuration for this engine.
// These fields are populated from the 'spec' field in forge.yaml.
type Spec struct {
	// Version of oapi-codegen to use (default v2.3.0)
	OapiCodegenVersion string `json:"oapiCodegenVersion,omitempty"`
}

// FromMap creates a Spec from a map[string]interface{}.
// This is used to parse the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// Parse oapiCodegenVersion
	if v, ok := m["oapiCodegenVersion"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.OapiCodegenVersion = val
		} else {
			return nil, fmt.Errorf("field oapiCodegenVersion: expected string, got %T", v)
		}
	}

	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
// This is used for serialization and testing.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})

	if s.OapiCodegenVersion != "" {
		m["oapiCodegenVersion"] = s.OapiCodegenVersion
	}

	return m
}
