// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml + spec.openapi.yaml
// SourceChecksum: sha256:8d20a6cfab2fb4622603c599d541f447713431484827f048c7f8fd6cc6269e94

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/enginecli"
	"github.com/alexandremahdhaoui/forge/pkg/forge"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// Name is the engine name.
const Name = "go-gen-openapi"

// Version information (set via ldflags during build).
var (
	Version        = "0.15.0"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

// main is the entry point for the go-gen-openapi engine.
func main() {
	enginecli.Bootstrap(enginecli.Config{
		Name:           Name,
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunCLI:         nil, // Generated engines are MCP-only
		RunMCP:         runMCPServer,
		DocsConfig:     docsConfig,
	})
}

// runMCPServer creates and runs the MCP server.
func runMCPServer() error {
	server, err := SetupMCPServer(Name, Version, Build)
	if err != nil {
		return fmt.Errorf("setting up MCP server: %w", err)
	}

	// Register docs MCP tools (docs-list, docs-get)
	if err := RegisterDocsMCPTools(server); err != nil {
		return fmt.Errorf("registering docs MCP tools: %w", err)
	}

	if err := server.Run(context.Background()); err != nil {
		return fmt.Errorf("running MCP server: %w", err)
	}

	return nil
}

// Build is the build function that must be implemented by the engine author.
// Signature: func(ctx context.Context, input mcptypes.BuildInput, spec *Spec) (*forge.Artifact, error)
// This is a placeholder - the actual implementation should be in a separate file.
var _ = func() BuildFunc {
	return func(_ context.Context, _ mcptypes.BuildInput, _ *Spec) (*forge.Artifact, error) {
		panic("Build function not implemented - create a separate file with the implementation")
	}
}
